$background = 151312
$onBackground = e8e1e0
$surface = 151312
$surfaceDim = 151312
$surfaceBright = 3c3838
$surfaceContainerLowest = 100e0d
$surfaceContainerLow = 1e1b1a
$surfaceContainer = 221f1e
$surfaceContainerHigh = 2c2929
$surfaceContainerHighest = 373433
$onSurface = e8e1e0
$surfaceVariant = 4f4442
$onSurfaceVariant = d3c3c0
$outline = 9c8e8b
$outlineVariant = 4f4442
$inverseSurface = e8e1e0
$inverseOnSurface = 33302f
$shadow = 000000
$scrim = 000000
$surfaceTint = e1bfb9
$primary = e1bfb9
$primaryDim = edcac3
$onPrimary = 412b27
$primaryContainer = 7b605b
$onPrimaryContainer = ffded8
$inversePrimary = 725853
$primaryFixed = fedbd4
$primaryFixedDim = e1bfb9
$onPrimaryFixed = 291713
$onPrimaryFixedVariant = 59413d
$secondary = d5c3bf
$secondaryDim = ecd9d5
$onSecondary = 392e2c
$secondaryContainer = 534644
$onSecondaryContainer = c6b5b1
$secondaryFixed = f1dedb
$secondaryFixedDim = d5c3bf
$onSecondaryFixed = 231917
$onSecondaryFixedVariant = 504442
$tertiary = d4c5a8
$tertiaryDim = f4e3c5
$onTertiary = 392f1b
$tertiaryContainer = 71654d
$onTertiaryContainer = f4e3c5
$tertiaryFixed = f1e1c3
$tertiaryFixedDim = d4c5a8
$onTertiaryFixed = 221b08
$onTertiaryFixedVariant = 504630
$error = ffb4ab
$errorDim = ff554a
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryPaletteKeyColor = 8d716c
$secondaryPaletteKeyColor = 837471
$tertiaryPaletteKeyColor = 71654d
$neutralPaletteKeyColor = 7b7675
$neutralVariantPaletteKeyColor = 817472
$errorPaletteKeyColor = de3730
$primary_paletteKeyColor = 8d716c
$secondary_paletteKeyColor = 837471
$tertiary_paletteKeyColor = 71654d
$neutral_paletteKeyColor = 7b7675
$neutral_variant_paletteKeyColor = 817472
$term0 = 353434
$term1 = ff563e
$term2 = ffbd9e
$term3 = ffdfd5
$term4 = b9ab66
$term5 = f18f8a
$term6 = ffba8d
$term7 = efd2c8
$term8 = b49e97
$term9 = ff8671
$term10 = ffd4c1
$term11 = fff1ed
$term12 = dcbc93
$term13 = ffa8a1
$term14 = ffd2b8
$term15 = ffffff
$rosewater = ffeeeb
$flamingo = ffd9d4
$pink = ffd2d1
$mauve = ffa9b1
$red = ff978f
$maroon = faaaa1
$peach = ffbfae
$yellow = ffeee8
$green = ffd8c1
$teal = ffdb94
$sky = ebd1ff
$sapphire = f2b2f2
$blue = ffa2bd
$lavender = ffbac7
$klink = bf6ba0
$klinkSelection = bf6ba0
$kvisited = ce5c67
$kvisitedSelection = ce5c68
$knegative = eb5445
$knegativeSelection = eb5447
$kneutral = ff8a6c
$kneutralSelection = ff8a6d
$kpositive = fd8c2a
$kpositiveSelection = fd8c2a
$text = e8e1e0
$subtext1 = d3c3c0
$subtext0 = 9c8e8b
$overlay2 = 887c79
$overlay1 = 736966
$overlay0 = 605856
$surface2 = 4e4745
$surface1 = 3b3735
$surface0 = 282523
$base = 151312
$mantle = 151312
$crust = 141211
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
