source=~/.config/hypr/hyprland/var.conf
# ================================ #
# Hyprland Execution Configuration
# ================================ #
# See https://wiki.hyprland.org/Configuring/Keywords/#executing

# -------------------------------- #
# Autostart necessary processes
# -------------------------------- #
# exec-once = swaync
# exec-once = systemctl --user start hyprpolkitagent
# exec-once = wl-paste --watch cliphist store
# exec-once = hyprpaper

# env = GTK_IM_MODULE,fcitx
env = QT_IM_MODULE,fcitx
env = XMODIFIERS,@im=fcitx
exec-once = fcitx5
# exec-once = waybar

# Core components (authentication, lock screen)
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Clipboard history
# exec-once = wl-paste --type text --watch cliphist store
# exec-once = wl-paste --type image --watch cliphist store

# Vicinae Launcher
exec-once = env QT_SCALE_FACTOR=1.5 vicinae server

# Auto delete trash 30 days old
# exec-once = trash-empty 30

# Location provider and night light
# exec-once = /usr/lib/geoclue-2.0/demos/agent
# exec-once = sleep 1 && gammastep

# Idle inhibit when audio playing
# exec-once = sway-audio-idle-inhibit --ignore-source-outputs cava

# Forward bluetooth media commands to MPRIS
exec-once = mpris-proxy

# Resize and move picture in picture windows
# exec-once = caelestia pip -d

# Regenerate hyprlock config on monitor changes
# exec = ~/.config/hypr/scripts/gen-hyprlock.fish
# exec-once = ~/.config/hypr/scripts/monitor-hyprlock.fish

# Reload hyprland when config changes (to regenerate everything)
# exec-once = ~/.config/hypr/scripts/monitor-config.fish


# Quickshell
env = QSG_RENDER_LOOP,threaded 
exec-once = caelestia shell
exec-once = qs -c overview
# exec-once = qs -c quickvoice

exec-once = hyprlock
exec-once = sunshine

# Bluetooth
exec-once = blueman-applet

# WiFi
exec-once = nm-applet

# Arch-Update
exec-once = arch-update --tray

# hyprpm
exec-once = hyprpm reload -n
exec-once = ~/.config/hypr/scripts/hyprkool_watchdog.sh
