-- ================================ --
-- Color Scheme
-- ================================ --
-- The active Material You palette, regenerated by caelestia-cli on scheme
-- changes. Since caelestia's lua-ification it writes scheme/current.lua
-- (a lua module returning { name = "hex", ... }); older versions wrote
-- scheme/current.conf in hyprlang `$name = value` form. Prefer the lua
-- module, fall back to parsing the legacy conf, so either cli version works.

local ok, scheme = pcall(require, "scheme.current")
if ok and type(scheme) == "table" then
    return scheme
end

-- Legacy fallback: parse hyprlang-style current.conf
local M = {}

local path = os.getenv("HOME") .. "/.config/hypr/scheme/current.conf"
local f = io.open(path, "r")
if f then
    for line in f:lines() do
        local k, v = line:match("^%s*%$([%w_]+)%s*=%s*(%S+)")
        if k and v then
            M[k] = v
        end
    end
    f:close()
end

return M
