-- ================================ --
-- Color Scheme
-- ================================ --
-- Parses ~/.config/hypr/scheme/current.conf, which holds the active
-- Material You palette. The file uses hyprlang-style `$name = value` lines
-- and is typically regenerated by the theming tool (e.g. caelestia / matugen),
-- so we keep it as the source of truth and parse it at config load.

local M = {}

local path = os.getenv("HOME") .. "/.config/hypr/scheme/current.conf"
local f = io.open(path, "r")
if f then
    for line in f:lines() do
        local k, v = line:match("^%s*%$([%w_]+)%s*=%s*(%S+)")
        if k and v then
            M[k] = v
        end
    end
    f:close()
end

return M
