-- ================================ --
-- Color Scheme
-- ================================ --
-- The active Material You palette, regenerated by the scheme tool on scheme
-- changes. The generator writes scheme/current.lua (a lua module returning
-- { name = "hex", ... }); older generators wrote scheme/current.conf in
-- hyprlang `$name = value` form. Prefer the lua module, fall back to parsing
-- the legacy conf, so either generation works.

local ok, scheme = pcall(require, "scheme.current")
if ok and type(scheme) == "table" then
    return scheme
end

-- Legacy fallback: parse hyprlang-style current.conf
local M = {}

local path = require("hyprland.util").hypr_dir() .. "/scheme/current.conf"
local f = io.open(path, "r")
if f then
    for line in f:lines() do
        local k, v = line:match("^%s*%$([%w_]+)%s*=%s*(%S+)")
        if k and v then
            M[k] = v
        end
    end
    f:close()
end

return M
